"""Type stub definitions for TokenTrieModel C-extension (PEP 484 / PEP 561)."""

from typing import Any, Dict, List, Optional, Tuple, Union, Iterable, Set

Token = Union[str, int]


class TokenBuffer:
    maxlen: int

    def __init__(self, maxlen: int) -> None: ...
    def append(self, item: Token) -> None: ...
    def extend(self, items: Iterable[Token]) -> None: ...
    def clear(self) -> None: ...
    @property
    def size(self) -> int: ...
    def to_tuple(self) -> Tuple[Token, ...]: ...
    def __getstate__(self) -> Dict[str, Any]: ...
    def __setstate__(self, state: Dict[str, Any]) -> None: ...


class TokenTrieNode:
    counts: Dict[Token, float]
    children: Dict[Token, TokenTrieNode]
    last_visit_step: int
    total_mass: float

    def __init__(self) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> TokenTrieNode: ...
    def __getstate__(self) -> Dict[str, Any]: ...
    def __setstate__(self, state: Dict[str, Any]) -> None: ...


class TokenTrieModel:
    # Configurable Hyperparameters (Public read/write attributes)
    max_depth: int
    min_depth: int
    depth_list: Optional[List[int]]
    decay: float
    skip_decay: bool
    alphabet_autoscale: bool
    fallback_mode: str
    pruning_mode: str
    pruning_step: int
    pruning_threshold: float
    max_beams: int
    cache_size: int
    smoothing_prior: float
    entropy_weighting: bool

    def __init__(
        self,
        max_depth: Optional[int] = 10,
        min_depth: Optional[int] = 1,
        depth_list: Optional[List[int]] = None,
        decay: Optional[float] = 0.99,
        alphabet_autoscale: bool = True,
        fallback_mode: str = "interpolated_unigram",
        pruning_mode: str = "fixed",
        pruning_step: int = 1000,
        pruning_threshold: float = 1e-6,
        max_beams: int = 1000,
        cache_size: int = 4096,
        smoothing_prior: float = 1e-3,
        entropy_weighting: bool = True,
    ) -> None: ...

    # --- Read-Only Model Properties (Protected Invariants) ---

    @property
    def step(self) -> int: ...

    @property
    def total_unigram_mass(self) -> float: ...

    @property
    def node_count(self) -> int: ...

    @property
    def vocab_size(self) -> int: ...
    
    @property
    def next_prune_target(self) -> int: ...

    @property
    def root(self) -> TokenTrieNode: ...

    @property
    def buffer(self) -> TokenBuffer: ...

    @property
    def known_vocabulary(self) -> Set[Token]: ...

    @property
    def unigram_counts(self) -> Dict[Token, float]: ...

    @property
    def valid_lengths(self) -> Set[int]: ...

    @property
    def log_scaling_base(self) -> float: ...

    # --- Core Lifecycle & Inference Methods ---

    def reset(self) -> TokenTrieModel: ...
    def update(self, actual: Token) -> None: ...
    def fit(self, X: Union[Iterable[Token], Iterable[Iterable[Token]]], verbose: bool = True) -> TokenTrieModel: ...

    def predict_proba(
        self,
        temperature: Union[float, str, None] = "none",
        top_k: Union[int, str, None] = "none",
        top_p: Union[float, str, None] = "none",
        masked_mode: str = "none",
        *,
        return_log_scores: bool = False,
    ) -> Dict[Token, float]: ...

    def predict(
        self,
        temperature: Union[float, str, None] = "none",
        top_k: Union[int, str, None] = "none",
        top_p: Union[float, str, None] = "none",
        masked_mode: str = "none",
    ) -> Optional[Token]: ...

    def score_transition(self, actual: Token) -> float: ...
    def score_sequence(self, sequence: List[Token], reduction: str = "mean_nll") -> float: ...

    def get_depth_entropy(self, depth: int) -> float: ...
    def get_depth_median(self, depth: int) -> float: ...
    def get_depth_stats(self) -> Dict[int, Dict[str, float]]: ...

    def prune_tree(self) -> None: ...
    def update_context(self, token: Token) -> None: ...
    def fill_context(self, context: Iterable[Token]) -> None: ...
    def reset_context(self) -> None: ...
    def reconfigure(self, params: Dict[str, Any]) -> TokenTrieModel: ...

    def set_branches(self, branches: Iterable[Tuple[Iterable[Token], Dict[Token, float]]]) -> TokenTrieModel: ...
    def delete_branches(self, sequences: Iterable[Iterable[Token]]) -> None: ...
    def merge(self, other: TokenTrieModel) -> TokenTrieModel: ...

    def save(self, filepath: str) -> None: ...
    @classmethod
    def load(cls, filepath: str) -> Optional[TokenTrieModel]: ...
    def save_json(self, filepath: str) -> None: ...
    @classmethod
    def load_json(cls, filepath: str) -> TokenTrieModel: ...

    def to_dict(self) -> Dict[str, Any]: ...
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> TokenTrieModel: ...
    def __getstate__(self) -> Dict[str, Any]: ...
    def __setstate__(self, state: Dict[str, Any]) -> None: ...